### ISSUE TITLE
Can not get a result

### ISSUE THREAD

**Issue by lgq-garbage** [tdelame/mcf_curve_skeletonizer#2]
the cmd screen always plays the saying:
"ImporterT: Face has equal vertices\n"
"ImporterT: Face has equal vertices\n"
"ImporterT: Face has equal vertices\n"
"ImporterT: Face has equal vertices\n"

I find it in mesh.cpp  428.
At the end, It will get out of memory.

**Comment by tdelame** [comment]
And your input mesh does not have degenerated faces (i.e. same vertex multiple times in the same face)?

**Comment by lgq-garbage** [comment]
> And your input mesh does not have degenerated faces (i.e. same vertex multiple times in the same face)?


I test four mesh. 
 The ball mesh with 50kb  can  get centerline.    
And other three bronchi mesh can not build.
it will give the message ".. faces failed, adding them as isolated faces"
and then  exit with code -1073740791     (out of memory)

Do it need to change code to use on bronchi mesh?

thank you for your Reply.

**Comment by tdelame** [comment]
I have not looked at this project for a long time ^^. Could you send me the mesh or point me to a link where I could download it? I'll try to check it this week-end.

**Comment by lgq-garbage** [comment]
I put the data in my repository.   https://github.com/lgq-garbage/meshdata   
sphere.off   is   the   ball mesh.

if you don't mind, could we exchange the way to contact?       
which one do you use?  (facebook, wechat or  twitter)

**Comment by tdelame** [comment]
It seems that your bron meshes files are ill-formed. Look at https://github.com/lgq-garbage/meshdata/blob/main/data/bronMesh2300.off#L1183, you always have 248 248 248 added to the face definitions. If I remember correctly, when defining faces you write the number of vertices and then the vertex indices of that face.

I mostly use mail, but I guess you could contact me through the Twitter account I linked to my github account.

**Comment by lgq-garbage** [comment]
Thanks guys! I have resolved this problem.
When I test the bron meshes, I find this code need the meshes are connected domains.
With your recommendation, I change the mesh definitions and repair the unconnected domains. After that, I run this code completely.

I will keep in touch with you by email.Really appreciate your help.

**Comment by lgq-garbage** [comment]
Hey, it's great to connect with you on Twitter! I've followed you and would love it if you could follow me back. Looking forward to sharing more tweets and updates together.  My ID is yujunwe39941840.
